name: psp_blue_light_filter

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"
          tags: pspbluelightfilter:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      # Building will also run clang-tidy and Cppcheck to analyse the code
      - name: Build code
        uses: addnab/docker-run-action@v3
        with:
          image: pspbluelightfilter:latest
          options: -v ${{ github.workspace }}:/work
          run: cd /work && .github/scripts/build.sh
      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: pspbluelightfilter:latest
          options: -v ${{ github.workspace }}:/work --shm-size 8G
          run: cd /work && pytest --pylint -vv -s tests/tests
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BlueLightFilter.prx
          path: build/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/BlueLightFilter.prx
